### ISSUE TITLE
The MessageContext param is useless

### ISSUE THREAD

**Issue by cedricfung** [MixinNetwork/bot-api-go-client#2]
May hide this param in the Context

https://github.com/MixinNetwork/bot-api-go-client/blob/5ed134c27da2c9582aa9968f9bfca5bfedf8ea89/blaze.go#L24

**Comment by crossle** [comment]
https://github.com/MixinNetwork/bot-api-go-client/commit/d6ba17782cb2cf6f56f9975d44ce892a6a468e84
