### ISSUE TITLE
CreateConversation return Internal Server Error

### ISSUE THREAD

**Issue by workingmin** [MixinNetwork/bot-api-go-client#88]
when i want to create conversation,  the code like that:
	conversation, err := bot.CreateConversation(ctx, "CONTACT", conversationId, "", "", participants, keystore.ClientId, keystore.SessionId, keystore.PrivateKey)
	if err != nil {
		panic(err)
	}
then the process throw: panic: {"status":500,"code":500,"description":"Internal Server Error"}

Is there some service wrong for China?
please help, thanks

**Comment by crossle** [comment]
please use bot.UniqueConversationId generate the conversationId

**Comment by workingmin** [comment]
the complete code like that：

type Keystore struct {
	Pin         string `json:"pin"`
	ClientId    string `json:"client_id"`
	SessionId   string `json:"session_id"`
	PinToken    string `json:"pin_token"`
	PrivateKey  string `json:"private_key"`
	RecipientId string `json:"recipient_id"`
}


func TestConversations(t *testing.T) {
	ctx := context.Background()

	f, err := os.Open("keystore.json")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	b, _ := io.ReadAll(f)
	var keystore Keystore
	json.Unmarshal(b, &keystore)

	conversationId := bot.UniqueConversationId(keystore.ClientId, keystore.RecipientId)
	participants := []bot.Participant{
		{
			UserId: keystore.ClientId,
			Role:   "OWNER",
		},
		{
			UserId: keystore.RecipientId,
			Role:   "",
		},
	}
	conversation, err := bot.CreateConversation(ctx, "CONTACT", conversationId, "", "", participants, keystore.ClientId, keystore.SessionId, keystore.PrivateKey)
	if err != nil {
		panic(err)
	}

	b, _ = json.Marshal(conversation)
	t.Logf(string(b))
}

**Comment by workingmin** [comment]
thank, it works.
